### ISSUE TITLE
Update Aglio NPM Dependency

### ISSUE THREAD

**Issue by brian-mann** [nnnnathann/gulp-aglio#2]
New version of aglio is 1.14.0.  There is a hash function set in `locals`, and some other updates.

**Comment by skawaguchi** [comment]
Aglio is now at 1.17.1.

**Comment by nnnnathann** [comment]
Thanks for keeping me up to date folks!

Updated the deps and added a badge so that I can keep track :)

**Comment by Anahkiasen** [comment]
Aglio 2 is out now, could we get a 0.8 :p

**Comment by nnnnathann** [comment]
yep, updated in 0.0.9, thanks
